overrides:
  bn.js@<4.12.3: '>=4.12.3'
  flatted@<3.4.0: '>=3.4.0'
  flatted@<=3.4.1: '>=3.4.2'
  serialize-javascript@<7.0.5: '>=7.0.5'
  serialize-javascript@<=7.0.2: '>=7.0.3'
  tmp@<=0.2.3: '>=0.2.4'
  ws@>=7.0.0 <7.5.10: '>=7.5.10'
