name: "🚀 release"

on:
  push:
    branches:
      - main

jobs:
  release:
    name: 🚀 release
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Setup repo
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 24.x
          registry-url: https://registry.npmjs.org
          cache: pnpm

      - name: Debug npm registry
        run: npm config get registry

      - name: Build app
        run: pnpm install --frozen-lockfile && pnpm run build:release

      - name: Audit dependencies
        run: pnpm audit --prod

      - name: 🚀 publish
        run: pnpm publish --access public --provenance --no-git-checks
